import { db } from "./db";
import { venues, marketCategoryEnum, venueTypeEnum, capacityCategoryEnum, genreEnum } from "../shared/schema";
import { eq, sql } from "drizzle-orm";

/**
 * Add custom venues to the database
 * This script adds a diverse set of indie venues with accurate geographic data
 * and detailed information about capacity, booking practices, and genre focus
 */
async function addCustomVenues() {
  console.log("Starting to add custom venues...");

  try {
    // First, check how many venues we already have
    const existingVenues = await db.select({ count: sql`count(*)` }).from(venues);
    const venueCount = Number(existingVenues[0].count);
    
    if (venueCount > 0) {
      console.log(`Found ${venueCount} existing venues. Skipping seed to avoid duplicates.`);
      console.log("If you want to re-seed, first delete existing venues or create a new clear-venues script.");
      return;
    }

    // Define venues by region to ensure good geographic distribution
    // Using real venues with accurate data for optimization features to work properly
    const venuesByRegion = {
      // Northeast
      northeast: [
        {
          name: "The Middle East",
          city: "Cambridge",
          region: "MA",
          latitude: 42.365770,
          longitude: -71.100494,
          marketCategory: "secondary",
          venueType: "club",
          capacity: 575,
          capacityCategory: "medium",
          primaryGenre: "indie",
          secondaryGenres: ["rock", "hip_hop"],
          bookingContactName: "Booking Manager",
          bookingEmail: "booking@mideastclub.com",
          contactPhone: "617-864-3278",
          typicalBookingLeadTime: 60,
          paymentStructure: "guarantee + door split",
          soundSystem: "Full PA with engineer",
          localAccommodation: false,
          localPromotion: true,
          description: "Multi-room venue with upstairs and downstairs performance spaces",
          ageRestriction: "18+",
          websiteUrl: "https://www.mideastoffers.com/"
        },
        {
          name: "Great Scott",
          city: "Boston",
          region: "MA",
          latitude: 42.351430, 
          longitude: -71.131660,
          marketCategory: "secondary",
          venueType: "bar",
          capacity: 240,
          capacityCategory: "small",
          primaryGenre: "indie",
          secondaryGenres: ["rock", "electronic"],
          bookingContactName: "Booking Team",
          bookingEmail: "booking@greatscottboston.com",
          contactPhone: "617-566-9014",
          typicalBookingLeadTime: 45,
          paymentStructure: "door split",
          soundSystem: "House system with engineer",
          localAccommodation: false,
          localPromotion: true,
          description: "Beloved small venue for local and touring indie acts",
          ageRestriction: "21+",
          websiteUrl: "https://www.greatscottboston.com/"
        },
        {
          name: "Baby's All Right",
          city: "Brooklyn",
          region: "NY",
          latitude: 40.710178,
          longitude: -73.963554,
          marketCategory: "primary",
          venueType: "club",
          capacity: 280,
          capacityCategory: "small",
          primaryGenre: "indie",
          secondaryGenres: ["electronic", "pop", "hip_hop"],
          bookingContactName: "Booking Team",
          bookingEmail: "booking@babysallright.com",
          contactPhone: "718-599-5800",
          typicalBookingLeadTime: 90,
          paymentStructure: "guarantee or door split",
          soundSystem: "Full PA with excellent monitors",
          localAccommodation: false,
          localPromotion: true,
          description: "Hip Brooklyn venue with restaurant and bar",
          ageRestriction: "21+",
          websiteUrl: "https://www.babysallright.com/"
        },
        {
          name: "Union Pool",
          city: "Brooklyn",
          region: "NY",
          latitude: 40.715244,
          longitude: -73.951911,
          marketCategory: "primary",
          venueType: "bar",
          capacity: 175,
          capacityCategory: "small",
          primaryGenre: "indie",
          secondaryGenres: ["rock", "folk"],
          bookingContactName: "Booking Manager",
          bookingEmail: "booking@union-pool.com",
          contactPhone: "718-609-0484",
          typicalBookingLeadTime: 60,
          paymentStructure: "door split",
          soundSystem: "Full PA with engineer",
          localAccommodation: false,
          localPromotion: true,
          description: "Former pool supply store turned music venue with outdoor patio",
          ageRestriction: "21+",
          websiteUrl: "https://union-pool.com/"
        },
        {
          name: "Johnny Brenda's",
          city: "Philadelphia", 
          region: "PA",
          latitude: 39.969330,
          longitude: -75.134703,
          marketCategory: "secondary",
          venueType: "bar",
          capacity: 250,
          capacityCategory: "small",
          primaryGenre: "indie",
          secondaryGenres: ["rock", "folk"],
          bookingContactName: "Booking Team",
          bookingEmail: "booking@johnnybrendas.com",
          contactPhone: "215-739-9684",
          typicalBookingLeadTime: 60,
          paymentStructure: "guarantee or door split",
          soundSystem: "Full PA with engineer",
          localAccommodation: false,
          localPromotion: true,
          description: "Cornerstone of Philly's Fishtown music scene with balcony viewing area",
          ageRestriction: "21+",
          websiteUrl: "https://www.johnnybrendas.com/"
        }
      ],
      
      // Midwest
      midwest: [
        {
          name: "Empty Bottle",
          city: "Chicago",
          region: "IL",
          latitude: 41.900456,
          longitude: -87.686638,
          marketCategory: "primary",
          venueType: "bar",
          capacity: 400,
          capacityCategory: "small",
          primaryGenre: "indie",
          secondaryGenres: ["rock", "experimental"],
          bookingContactName: "Booking Manager",
          bookingEmail: "booking@emptybottle.com",
          contactPhone: "773-276-3600",
          typicalBookingLeadTime: 90,
          paymentStructure: "guarantee or door split",
          soundSystem: "Full PA with engineer",
          localAccommodation: false,
          localPromotion: true,
          description: "Chicago institution for underground and indie music since 1992",
          ageRestriction: "21+",
          websiteUrl: "https://www.emptybottle.com/"
        },
        {
          name: "Schubas Tavern",
          city: "Chicago",
          region: "IL",
          latitude: 41.939266,
          longitude: -87.653769,
          marketCategory: "primary",
          venueType: "bar",
          capacity: 200,
          capacityCategory: "small",
          primaryGenre: "indie",
          secondaryGenres: ["folk", "rock"],
          bookingContactName: "Booking Team",
          bookingEmail: "booking@schubas.com",
          contactPhone: "773-525-2508",
          typicalBookingLeadTime: 60,
          paymentStructure: "door split",
          soundSystem: "Full PA with engineer",
          localAccommodation: false,
          localPromotion: true,
          description: "Historic landmark building with intimate performance space",
          ageRestriction: "21+",
          websiteUrl: "https://www.lh-st.com/venues/schubas-tavern/"
        },
        {
          name: "7th St Entry",
          city: "Minneapolis",
          region: "MN",
          latitude: 44.978543,
          longitude: -93.276391,
          marketCategory: "secondary",
          venueType: "club",
          capacity: 250,
          capacityCategory: "small",
          primaryGenre: "indie",
          secondaryGenres: ["rock", "punk"],
          bookingContactName: "Booking Team",
          bookingEmail: "booking@first-avenue.com",
          contactPhone: "612-338-8388",
          typicalBookingLeadTime: 60,
          paymentStructure: "guarantee or door split",
          soundSystem: "Full PA with engineer",
          localAccommodation: false,
          localPromotion: true,
          description: "Smaller sister venue to the iconic First Avenue",
          ageRestriction: "18+",
          websiteUrl: "https://first-avenue.com/venue/7th-st-entry/"
        },
        {
          name: "The Loving Touch",
          city: "Ferndale",
          region: "MI",
          latitude: 42.460255,
          longitude: -83.134300,
          marketCategory: "tertiary",
          venueType: "bar",
          capacity: 300,
          capacityCategory: "small",
          primaryGenre: "indie",
          secondaryGenres: ["rock", "electronic"],
          bookingContactName: "Booking Manager",
          bookingEmail: "booking@thelovingtouchferndale.com",
          contactPhone: "248-820-5596",
          typicalBookingLeadTime: 45,
          paymentStructure: "door split",
          soundSystem: "Full PA with engineer",
          localAccommodation: false,
          localPromotion: true,
          description: "Former massage parlor turned music venue",
          ageRestriction: "21+",
          websiteUrl: "https://www.thelovingtouchferndale.com/"
        },
        {
          name: "Ace of Cups",
          city: "Columbus",
          region: "OH",
          latitude: 40.014709,
          longitude: -83.012661,
          marketCategory: "tertiary",
          venueType: "bar",
          capacity: 300,
          capacityCategory: "small",
          primaryGenre: "indie",
          secondaryGenres: ["rock", "punk"],
          bookingContactName: "Booking Team",
          bookingEmail: "booking@aceofcupsbar.com",
          contactPhone: "614-262-6001",
          typicalBookingLeadTime: 45,
          paymentStructure: "door split",
          soundSystem: "Full PA with engineer",
          localAccommodation: true,
          localPromotion: true,
          description: "Rock club that also serves vegan food",
          ageRestriction: "18+",
          websiteUrl: "http://www.aceofcupsbar.com/"
        }
      ],
      
      // South
      south: [
        {
          name: "9:30 Club",
          city: "Washington",
          region: "DC",
          latitude: 38.918198,
          longitude: -77.023361,
          marketCategory: "primary",
          venueType: "club",
          capacity: 1200,
          capacityCategory: "large",
          primaryGenre: "indie",
          secondaryGenres: ["rock", "hip_hop", "electronic"],
          bookingContactName: "Booking Team",
          bookingEmail: "booking@930.com",
          contactPhone: "202-265-0930",
          typicalBookingLeadTime: 120,
          paymentStructure: "guarantee",
          soundSystem: "World-class PA with engineer",
          localAccommodation: false,
          localPromotion: true,
          description: "Legendary venue consistently rated among the best in the country",
          ageRestriction: "All ages",
          websiteUrl: "https://www.930.com/"
        },
        {
          name: "Cat's Cradle",
          city: "Carrboro",
          region: "NC",
          latitude: 35.910175,
          longitude: -79.075363,
          marketCategory: "tertiary",
          venueType: "club",
          capacity: 750,
          capacityCategory: "medium",
          primaryGenre: "indie",
          secondaryGenres: ["rock", "folk"],
          bookingContactName: "Booking Manager",
          bookingEmail: "booking@catscradle.com",
          contactPhone: "919-967-9053",
          typicalBookingLeadTime: 90,
          paymentStructure: "guarantee or door split",
          soundSystem: "Full PA with engineer",
          localAccommodation: false,
          localPromotion: true,
          description: "Influential club that's been supporting indie music since 1969",
          ageRestriction: "All ages",
          websiteUrl: "https://catscradle.com/"
        },
        {
          name: "The Earl",
          city: "Atlanta",
          region: "GA",
          latitude: 33.740665,
          longitude: -84.346465,
          marketCategory: "secondary",
          venueType: "bar",
          capacity: 300,
          capacityCategory: "small",
          primaryGenre: "indie",
          secondaryGenres: ["rock", "punk"],
          bookingContactName: "Booking Team",
          bookingEmail: "booking@badearl.com",
          contactPhone: "404-522-3950",
          typicalBookingLeadTime: 60,
          paymentStructure: "door split",
          soundSystem: "Full PA with engineer",
          localAccommodation: false,
          localPromotion: true,
          description: "Restaurant and bar with separate music room",
          ageRestriction: "21+",
          websiteUrl: "https://www.badearl.com/"
        },
        {
          name: "The EARL",
          city: "Austin",
          region: "TX",
          latitude: 30.263674,
          longitude: -97.736504,
          marketCategory: "secondary",
          venueType: "club",
          capacity: 270,
          capacityCategory: "small",
          primaryGenre: "indie",
          secondaryGenres: ["rock", "country"],
          bookingContactName: "Booking Team",
          bookingEmail: "booking@mohawkaustin.com",
          contactPhone: "512-666-0877",
          typicalBookingLeadTime: 60,
          paymentStructure: "guarantee or door split",
          soundSystem: "Full PA with engineer",
          localAccommodation: false,
          localPromotion: true,
          description: "Multi-level venue with indoor and outdoor stages",
          ageRestriction: "All ages",
          websiteUrl: "https://mohawkaustin.com/"
        },
        {
          name: "Saturn",
          city: "Birmingham",
          region: "AL",
          latitude: 33.513901,
          longitude: -86.800819,
          marketCategory: "tertiary",
          venueType: "club",
          capacity: 550,
          capacityCategory: "medium",
          primaryGenre: "indie",
          secondaryGenres: ["rock", "electronic"],
          bookingContactName: "Booking Manager",
          bookingEmail: "booking@saturnbirmingham.com",
          contactPhone: "205-703-9545",
          typicalBookingLeadTime: 60,
          paymentStructure: "guarantee or door split",
          soundSystem: "Full PA with engineer",
          localAccommodation: false,
          localPromotion: true,
          description: "Space-themed venue with coffee shop attached",
          ageRestriction: "18+",
          websiteUrl: "https://www.saturnbirmingham.com/"
        }
      ],
      
      // West
      west: [
        {
          name: "Neumos",
          city: "Seattle",
          region: "WA",
          latitude: 47.613869,
          longitude: -122.314800,
          marketCategory: "secondary",
          venueType: "club",
          capacity: 650,
          capacityCategory: "medium",
          primaryGenre: "indie",
          secondaryGenres: ["rock", "electronic"],
          bookingContactName: "Booking Team",
          bookingEmail: "booking@neumos.com",
          contactPhone: "206-709-9467",
          typicalBookingLeadTime: 90,
          paymentStructure: "guarantee or door split",
          soundSystem: "Full PA with engineer",
          localAccommodation: false,
          localPromotion: true,
          description: "Capitol Hill mainstay with excellent sound",
          ageRestriction: "All ages",
          websiteUrl: "https://www.neumos.com/"
        },
        {
          name: "Doug Fir Lounge",
          city: "Portland",
          region: "OR",
          latitude: 45.522728,
          longitude: -122.657249,
          marketCategory: "secondary",
          venueType: "club",
          capacity: 300,
          capacityCategory: "small",
          primaryGenre: "indie",
          secondaryGenres: ["folk", "rock"],
          bookingContactName: "Booking Team",
          bookingEmail: "booking@dougfirlounge.com",
          contactPhone: "503-231-9663",
          typicalBookingLeadTime: 60,
          paymentStructure: "guarantee or door split",
          soundSystem: "Full PA with engineer",
          localAccommodation: true,
          localPromotion: true,
          description: "Log cabin-themed venue with restaurant and hotel upstairs",
          ageRestriction: "21+",
          websiteUrl: "https://www.dougfirlounge.com/"
        },
        {
          name: "The Independent",
          city: "San Francisco",
          region: "CA",
          latitude: 37.775459,
          longitude: -122.437546,
          marketCategory: "primary",
          venueType: "club",
          capacity: 500,
          capacityCategory: "medium",
          primaryGenre: "indie",
          secondaryGenres: ["rock", "electronic"],
          bookingContactName: "Booking Team",
          bookingEmail: "booking@theindependentsf.com",
          contactPhone: "415-771-1421",
          typicalBookingLeadTime: 90,
          paymentStructure: "guarantee",
          soundSystem: "Full PA with engineer",
          localAccommodation: false,
          localPromotion: true,
          description: "Intimate venue with excellent acoustics",
          ageRestriction: "21+",
          websiteUrl: "https://www.theindependentsf.com/"
        },
        {
          name: "The Echo",
          city: "Los Angeles",
          region: "CA",
          latitude: 34.078827,
          longitude: -118.260609,
          marketCategory: "primary",
          venueType: "club",
          capacity: 350,
          capacityCategory: "small",
          primaryGenre: "indie",
          secondaryGenres: ["rock", "electronic"],
          bookingContactName: "Booking Manager",
          bookingEmail: "booking@spacelandpresents.com",
          contactPhone: "213-413-8200",
          typicalBookingLeadTime: 90,
          paymentStructure: "guarantee or door split",
          soundSystem: "Full PA with engineer",
          localAccommodation: false,
          localPromotion: true,
          description: "Echo Park venue that hosts indie bands on the rise",
          ageRestriction: "18+",
          websiteUrl: "https://www.spacelandpresents.com/venues/the-echo/"
        },
        {
          name: "Treefort Music Hall",
          city: "Boise",
          region: "ID",
          latitude: 43.616616,
          longitude: -116.203016,
          marketCategory: "tertiary",
          venueType: "club",
          capacity: 300,
          capacityCategory: "small",
          primaryGenre: "indie",
          secondaryGenres: ["folk", "experimental"],
          bookingContactName: "Booking Team",
          bookingEmail: "booking@treefortmusic.com",
          contactPhone: "208-789-5817",
          typicalBookingLeadTime: 60,
          paymentStructure: "door split",
          soundSystem: "Full PA with engineer",
          localAccommodation: true,
          localPromotion: true,
          description: "Year-round venue operated by the Treefort Music Festival team",
          ageRestriction: "All ages",
          websiteUrl: "https://www.treefortmusicfest.com/"
        }
      ],
      
      // College Towns
      collegeTowns: [
        {
          name: "The Bishop",
          city: "Bloomington",
          region: "IN",
          latitude: 39.166447,
          longitude: -86.534157,
          marketCategory: "tertiary",
          venueType: "bar",
          capacity: 200,
          capacityCategory: "small",
          primaryGenre: "indie",
          secondaryGenres: ["rock", "folk"],
          bookingContactName: "Booking Manager",
          bookingEmail: "booking@thebishopbar.com",
          contactPhone: "812-333-4700",
          typicalBookingLeadTime: 45,
          paymentStructure: "door split",
          soundSystem: "Full PA with engineer",
          localAccommodation: true,
          localPromotion: true,
          description: "Intimate venue in a college town with strong music scene",
          ageRestriction: "21+",
          websiteUrl: "https://www.thebishopbar.com/"
        },
        {
          name: "The Blind Pig",
          city: "Ann Arbor",
          region: "MI",
          latitude: 42.280497,
          longitude: -83.749002,
          marketCategory: "tertiary",
          venueType: "bar",
          capacity: 400,
          capacityCategory: "small",
          primaryGenre: "indie",
          secondaryGenres: ["rock", "punk"],
          bookingContactName: "Booking Team",
          bookingEmail: "booking@blindpigmusic.com",
          contactPhone: "734-996-8555",
          typicalBookingLeadTime: 45,
          paymentStructure: "door split",
          soundSystem: "Full PA with engineer",
          localAccommodation: false,
          localPromotion: true,
          description: "Historic college town venue that's hosted numerous famous acts",
          ageRestriction: "18+",
          websiteUrl: "https://www.blindpigmusic.com/"
        },
        {
          name: "40 Watt Club",
          city: "Athens",
          region: "GA",
          latitude: 33.957634,
          longitude: -83.377863,
          marketCategory: "tertiary",
          venueType: "club",
          capacity: 500,
          capacityCategory: "medium",
          primaryGenre: "indie",
          secondaryGenres: ["rock", "alternative"],
          bookingContactName: "Booking Manager",
          bookingEmail: "booking@40watt.com",
          contactPhone: "706-549-7871",
          typicalBookingLeadTime: 60,
          paymentStructure: "guarantee or door split",
          soundSystem: "Full PA with engineer",
          localAccommodation: false,
          localPromotion: true,
          description: "Legendary Athens venue that helped launch R.E.M. and many others",
          ageRestriction: "18+",
          websiteUrl: "http://www.40watt.com/"
        },
        {
          name: "The Depot",
          city: "Blacksburg",
          region: "VA",
          latitude: 37.229572,
          longitude: -80.414186,
          marketCategory: "tertiary",
          venueType: "college_venue",
          capacity: 300,
          capacityCategory: "small",
          primaryGenre: "indie",
          secondaryGenres: ["rock", "electronic"],
          bookingContactName: "Booking Team",
          bookingEmail: "booking@uusa.vt.edu",
          contactPhone: "540-231-6120",
          typicalBookingLeadTime: 60,
          paymentStructure: "guarantee",
          soundSystem: "Full PA with engineer",
          localAccommodation: false,
          localPromotion: true,
          description: "Virginia Tech's on-campus music venue",
          ageRestriction: "All ages",
          websiteUrl: "https://www.uusa.vt.edu/the-depot/"
        },
        {
          name: "The Cavern Club",
          city: "Madison",
          region: "WI",
          latitude: 43.074959,
          longitude: -89.394592,
          marketCategory: "tertiary",
          venueType: "club",
          capacity: 250,
          capacityCategory: "small",
          primaryGenre: "indie",
          secondaryGenres: ["rock", "folk"],
          bookingContactName: "Booking Team",
          bookingEmail: "booking@highnoonsaloon.com",
          contactPhone: "608-268-1122",
          typicalBookingLeadTime: 45,
          paymentStructure: "door split",
          soundSystem: "Full PA with engineer",
          localAccommodation: true,
          localPromotion: true,
          description: "Underground venue with a strong local music focus",
          ageRestriction: "18+",
          websiteUrl: "https://high-noon.com/"
        }
      ],
      
      // DIY and Alt Spaces
      diySpaces: [
        {
          name: "Silent Barn",
          city: "Brooklyn",
          region: "NY",
          latitude: 40.70673,
          longitude: -73.92609,
          marketCategory: "primary",
          venueType: "diy_space",
          capacity: 150,
          capacityCategory: "tiny",
          primaryGenre: "indie",
          secondaryGenres: ["experimental", "punk"],
          bookingContactName: "Collective",
          bookingEmail: "booking@silentbarn.org",
          contactPhone: null,
          typicalBookingLeadTime: 30,
          paymentStructure: "door split",
          soundSystem: "Basic PA system",
          localAccommodation: true,
          localPromotion: true,
          description: "Artist-run space with living quarters and performance venue",
          ageRestriction: "All ages",
          websiteUrl: "http://silentbarn.org/"
        },
        {
          name: "The Vera Project",
          city: "Seattle",
          region: "WA",
          latitude: 47.622143,
          longitude: -122.354613,
          marketCategory: "secondary",
          venueType: "community_center",
          capacity: 225,
          capacityCategory: "small",
          primaryGenre: "indie",
          secondaryGenres: ["punk", "experimental"],
          bookingContactName: "Booking Coordinator",
          bookingEmail: "booking@theveraproject.org",
          contactPhone: "206-956-8372",
          typicalBookingLeadTime: 45,
          paymentStructure: "door split",
          soundSystem: "Full PA with volunteer engineers",
          localAccommodation: false,
          localPromotion: true,
          description: "All-ages, volunteer-run arts and music space",
          ageRestriction: "All ages",
          websiteUrl: "https://theveraproject.org/"
        },
        {
          name: "Subterranean Arthouse",
          city: "Berkeley",
          region: "CA",
          latitude: 37.865543,
          longitude: -122.269705,
          marketCategory: "secondary",
          venueType: "art_gallery",
          capacity: 100,
          capacityCategory: "tiny",
          primaryGenre: "experimental",
          secondaryGenres: ["folk", "world"],
          bookingContactName: "Arts Coordinator",
          bookingEmail: "booking@subterraneanarthouse.org",
          contactPhone: null,
          typicalBookingLeadTime: 30,
          paymentStructure: "door split",
          soundSystem: "Basic PA system",
          localAccommodation: false,
          localPromotion: true,
          description: "Multi-arts venue hosting experimental music and performances",
          ageRestriction: "All ages",
          websiteUrl: "http://subterraneanarthouse.org/"
        },
        {
          name: "Rubber Gloves",
          city: "Denton",
          region: "TX",
          latitude: 33.215173,
          longitude: -97.128754,
          marketCategory: "tertiary",
          venueType: "bar",
          capacity: 150,
          capacityCategory: "tiny",
          primaryGenre: "indie",
          secondaryGenres: ["punk", "experimental"],
          bookingContactName: "Booking Manager",
          bookingEmail: "booking@rubberglovesdentontx.com",
          contactPhone: "940-594-0269",
          typicalBookingLeadTime: 30,
          paymentStructure: "door split",
          soundSystem: "Full PA with engineer",
          localAccommodation: true,
          localPromotion: true,
          description: "Dive bar venue that's a staple of Denton's music scene",
          ageRestriction: "21+",
          websiteUrl: "https://www.rubberglovesdentontx.com/"
        },
        {
          name: "Charm City Art Space",
          city: "Baltimore",
          region: "MD",
          latitude: 39.312119,
          longitude: -76.621552,
          marketCategory: "secondary",
          venueType: "diy_space",
          capacity: 100,
          capacityCategory: "tiny",
          primaryGenre: "punk",
          secondaryGenres: ["indie", "experimental"],
          bookingContactName: "Collective",
          bookingEmail: "booking@charmcityartspace.org",
          contactPhone: null,
          typicalBookingLeadTime: 30,
          paymentStructure: "door split",
          soundSystem: "Basic PA system",
          localAccommodation: true,
          localPromotion: true,
          description: "Volunteer-run DIY space focused on all-ages shows",
          ageRestriction: "All ages",
          websiteUrl: "http://www.charmcityartspace.org/"
        }
      ],
      
      // Unique/Specialist Venues
      specialistVenues: [
        {
          name: "Sonic Lunch",
          city: "Ann Arbor",
          region: "MI",
          latitude: 42.279594,
          longitude: -83.749240,
          marketCategory: "tertiary",
          venueType: "community_center",
          capacity: 500,
          capacityCategory: "medium",
          primaryGenre: "indie",
          secondaryGenres: ["folk", "rock"],
          bookingContactName: "Event Coordinator",
          bookingEmail: "booking@soniclunch.com",
          contactPhone: null,
          typicalBookingLeadTime: 90,
          paymentStructure: "guarantee",
          soundSystem: "Temporary outdoor system",
          localAccommodation: false,
          localPromotion: true,
          description: "Summer concert series at Liberty Plaza",
          ageRestriction: "All ages",
          websiteUrl: "https://soniclunch.com/"
        },
        {
          name: "Drkmttr Collective",
          city: "Nashville",
          region: "TN",
          latitude: 36.183632,
          longitude: -86.750010,
          marketCategory: "secondary",
          venueType: "diy_space",
          capacity: 120,
          capacityCategory: "tiny",
          primaryGenre: "indie",
          secondaryGenres: ["punk", "experimental"],
          bookingContactName: "Collective",
          bookingEmail: "booking@drkmttrcollective.com",
          contactPhone: null,
          typicalBookingLeadTime: 30,
          paymentStructure: "door split",
          soundSystem: "Basic PA system",
          localAccommodation: true,
          localPromotion: true,
          description: "All-ages DIY venue and collective in East Nashville",
          ageRestriction: "All ages",
          websiteUrl: "https://www.drkmttrcollective.com/"
        },
        {
          name: "Cafe Mustache",
          city: "Chicago",
          region: "IL",
          latitude: 41.919102,
          longitude: -87.697152,
          marketCategory: "primary",
          venueType: "coffeehouse",
          capacity: 75,
          capacityCategory: "tiny",
          primaryGenre: "folk",
          secondaryGenres: ["indie", "experimental"],
          bookingContactName: "Events Coordinator",
          bookingEmail: "booking@cafemustache.com",
          contactPhone: "773-206-8589",
          typicalBookingLeadTime: 30,
          paymentStructure: "door split",
          soundSystem: "Small PA system",
          localAccommodation: false,
          localPromotion: true,
          description: "Coffee shop with evening performances and vinyl selection",
          ageRestriction: "All ages",
          websiteUrl: "http://cafemustache.com/"
        },
        {
          name: "Grimey's",
          city: "Nashville",
          region: "TN",
          latitude: 36.126968,
          longitude: -86.767729,
          marketCategory: "secondary",
          venueType: "record_store",
          capacity: 100,
          capacityCategory: "tiny",
          primaryGenre: "indie",
          secondaryGenres: ["folk", "rock"],
          bookingContactName: "Events Manager",
          bookingEmail: "events@grimeys.com",
          contactPhone: "615-254-4801",
          typicalBookingLeadTime: 30,
          paymentStructure: "no payment (promo)",
          soundSystem: "Small PA system",
          localAccommodation: false,
          localPromotion: true,
          description: "Popular record store with in-store performances",
          ageRestriction: "All ages",
          websiteUrl: "https://www.grimeys.com/"
        },
        {
          name: "Mississippi Studios",
          city: "Portland",
          region: "OR",
          latitude: 45.550930,
          longitude: -122.676445,
          marketCategory: "secondary",
          venueType: "club",
          capacity: 250,
          capacityCategory: "small",
          primaryGenre: "indie",
          secondaryGenres: ["folk", "rock"],
          bookingContactName: "Booking Team",
          bookingEmail: "booking@mississippistudios.com",
          contactPhone: "503-288-3895",
          typicalBookingLeadTime: 60,
          paymentStructure: "guarantee or door split",
          soundSystem: "Full PA with engineer",
          localAccommodation: false,
          localPromotion: true,
          description: "Former recording studio converted to an intimate music venue",
          ageRestriction: "21+",
          websiteUrl: "https://www.mississippistudios.com/"
        }
      ]
    };
    
    // Combine all venues into a single array
    const allVenues = [
      ...venuesByRegion.northeast,
      ...venuesByRegion.midwest,
      ...venuesByRegion.south,
      ...venuesByRegion.west,
      ...venuesByRegion.collegeTowns,
      ...venuesByRegion.diySpaces,
      ...venuesByRegion.specialistVenues
    ];
    
    console.log(`Preparing to add ${allVenues.length} custom venues to database...`);
    
    // Insert venues into the database
    let addedCount = 0;
    for (const venueData of allVenues) {
      try {
        await db.insert(venues).values({
          name: venueData.name,
          city: venueData.city,
          region: venueData.region,
          country: "US",
          latitude: venueData.latitude,
          longitude: venueData.longitude,
          marketCategory: venueData.marketCategory,
          venueType: venueData.venueType,
          capacity: venueData.capacity,
          capacityCategory: venueData.capacityCategory,
          primaryGenre: venueData.primaryGenre,
          secondaryGenres: venueData.secondaryGenres,
          bookingContactName: venueData.bookingContactName,
          bookingEmail: venueData.bookingEmail,
          contactPhone: venueData.contactPhone,
          contactEmail: null, // Using bookingEmail as primary contact
          typicalBookingLeadTime: venueData.typicalBookingLeadTime,
          paymentStructure: venueData.paymentStructure,
          soundSystem: venueData.soundSystem,
          localAccommodation: venueData.localAccommodation,
          localPromotion: venueData.localPromotion,
          description: venueData.description,
          ageRestriction: venueData.ageRestriction,
          websiteUrl: venueData.websiteUrl,
          imageUrl: null, // Could add default images in the future
          socialMediaLinks: null,
          bandsintownId: null, // To be filled in when API access is available
          songkickId: null,
          ownerId: null,
          createdAt: new Date(),
          updatedAt: new Date()
        });
        addedCount++;
        console.log(`Added venue: ${venueData.name} in ${venueData.city}, ${venueData.region}`);
      } catch (error) {
        console.error(`Error adding venue ${venueData.name}:`, error);
      }
    }
    
    console.log(`Successfully added ${addedCount} venues to the database.`);
    
  } catch (error) {
    console.error("Error in addCustomVenues:", error);
  }
}

// Execute the function
addCustomVenues()
  .catch(error => {
    console.error("Failed to add custom venues:", error);
    process.exit(1);
  })
  .finally(() => {
    console.log("Custom venue seeding process completed");
    process.exit(0);
  });